comment/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/24

from django.urls import path
from . import views
app_name = 'comment'
urlpatterns = [
    path('submit_comment', views.submit_comment, name='submit_comment'),
]

demo1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import ckeditor_uploader
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('comic/', include('comic.urls')),
    path('', views.home, name='home'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topic/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/24

from django.urls import path, include
from . import views
app_name = 'topic'
urlpatterns = [
    path('', views.topic_index, name='topic_index'),
    path('<int:pk>', views.topic_detail, name='topic_detail'),
    # path('add_topic', views.add_topic, name='add_topic'),
    path('type/<int:type_pk>', views.topics_with_type, name='topisc_with_type'),
]

user/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/27


from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('register/', views.register, name='register'),
    path('user_join', views.user_join, name='user_join'),
]

topic/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class TopicType(models.Model):
    type_name = models.CharField(max_length=20)
    type_introduction = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='topic_type_images/', null=True, blank=True)

    def __str__(self):
        return self.type_name


class Topic(models.Model):
    title = models.CharField(max_length=255)
    topic_type = models.ForeignKey(TopicType, on_delete=models.CASCADE,related_name='topic_type')
    content = RichTextUploadingField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creator',null=True,blank=True)
    last_modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "<Topic:%s>" % self.title

topic/forms.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/28

from django import forms
from django.contrib.contenttypes.models import ContentType
from django.db.models import ObjectDoesNotExist
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Topic, TopicType


class TopicForm(forms.ModelForm):
    title = forms.CharField(
        label='标题',
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'bg-light form-control',
        })
    )
    # content = forms.CharField(widget=CKEditorWidget(config_name='topic_ckeditor'),)
    content = forms.CharField(label='内容', widget=CKEditorUploadingWidget(config_name='topic_ckeditor'))
    topic_type = forms.ModelChoiceField(
        label='分类',
        queryset=TopicType.objects.all(),
        widget=forms.Select(attrs={
            'class': 'bg-light custom-select',
        })
    )
    class Meta:
        model = Topic
        fields = ['title', 'content', 'topic_type']


    # def __init__(self, *args, **kwargs):
    #     if 'creator' in kwargs:
    #         self.creator = kwargs.pop('creator')
    #     super(TopicForm, self).__init__(*args, **kwargs)
    #
    # def clean(self):
    #     if self.user.is_authenticated:
    #         self.cleaned_data['creator'] = self.creator
    #     else:
    #         raise forms.ValidationError('用户尚未登录')

# class TopicForm(forms.Form):
#     topic_type = forms.ChoiceField(widget=forms.RadioSelect, choices=TopicType.objects.all())
#     title = forms.CharField(widget=forms.CharField)
#     content = forms.CharField(widget=CKEditorWidget(config_name='topic_ckeditor'))
#
#     def __init__(self, *args, **kwargs):
#         if 'user' in kwargs:
#             self.user = kwargs.pop('user')
#         super(TopicForm, self).__init__(*args, **kwargs)
#
#     def clean(self):
#         if self.user.is_authenticated:
#             self.cleaned_data['user'] = self.user
#         else:
#             raise forms.ValidationError('用户尚未登录')

topic/views.py
from django.shortcuts import render, get_object_or_404
from .models import Topic, TopicType
from .forms import TopicForm
from django.http import JsonResponse

# Create your views here.


def topics_with_type(request, type_pk):
    topic_type = get_object_or_404(TopicType,pk=type_pk)
    topics = Topic.objects.filter(topic_type=topic_type)
    context = {
        'topics': topics,
        'topic_type': topic_type,
    }
    return render(request, 'topics_with_type.html', context)


def topic_index(request):
    if request.method == 'POST':
        topic_form = TopicForm(request.POST)
        if topic_form.is_valid():
            topic = topic_form.save(commit=False)
            topic.creator = request.user
            topic.save()

    topics = Topic.objects.all().order_by('-created_time')
    context = {
        'topics': topics,
        'topic_form': TopicForm(),

    }
    return render(request, 'topic_index.html', context)


def topic_detail(request, pk):
    topic = get_object_or_404(Topic, pk=pk)
    context = {
        'topic': topic,
    }
    return render(request, 'topic_detail.html', context)


# def add_topic(request):
#     topic_form = TopicForm(request.POST)
#     data={}
#     if topic_form.is_valid():
#         topic = topic_form.save(commit=False)
#         topic.creator = request.user
#         # topic = Topic()
#         # topic.content=topic_form.cleaned_data['content']
#         # topic.title=topic_form.cleaned_data['title']
#         # topic.creator=topic_form.cleaned_data['user']
#         # topic.topic_type=topic_form.cleaned_data['topic_type']
#         data['status']='SUCCESS'
#         # data['username'] = topic.creator
#         # data['created_time'] = topic.created_time
#         # data['pk'] = topic.pk
#         topic.save()
#
#     else:
#         data['status'] = 'ERROR'
#         data['message'] = list(topic_form.errors())[0][0]
#
#     return JsonResponse(data, safe=False)

topic/templates/testcss.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'topic/topic.css' %}">
</head>
<body>
    <h1><a href="/">hello</a></h1>
    <ion-icon name="thumbs-up-outline" size="large"></ion-icon>
    <ion-icon src="/path/to/external/file.svg"></ion-icon>
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
</body>
</html>

topic/templates/topic_detail.html
{% extends 'base.html' %}
{% load comment_tags %}
{% load likes_tags %}
{% block title%}
    讨论
{% endblock %}
{% block header_extends %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'topic/topic.css' %}">
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block content %}
    <section>
    <div class="py-3">
        <h2 class="text-center">{{ topic.title }}</h2>
    </div>
    <div class="container w-50">
        <div class="bg-light border rounded p-3">
             <small>
                {{ topic.created_time.date }}|&nbsp;
                分类:
                <a href="{% url 'topic:topisc_with_type' topic.topic_type.pk %}">
                <span class="font-weight-normal text-secondary" title="{{ topic.topic_type.type_introduction|safe }}"
                      data-toggle="tooltip" data-html="true" data-placement="top">{{ topic.topic_type }}</span>
                </a>
            </small>
            <div class="p-3">
                <p>{{ topic.content|safe }}</p>
            </div>
            <div>
                <span class="small">评论数: &nbsp;</span><span>{% get_comment_count topic %}</span>
                <div class="like" onclick="likeChange(this, '{% get_content_type topic %}', {{ topic.pk }})">
                    <ion-icon name="thumbs-up-outline" class="{% get_like_status topic %}" size="small" ></ion-icon>
                    <span class="liked-num">{% get_like_count topic %}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="container w-50">
        <h3>提交评论</h3>
        {% if user.is_authenticated %}
            <form action="{% url 'comment:submit_comment' %}" method="POST" id="comment_form">
                 <label>{{ user.username }}，欢迎评论</label>
                <div id="reply_content_container" style="display: none">
                    <p>回复：</p>
                    <div id="replay_content"></div>
                </div>
                {% csrf_token %}
            {% get_comment_form topic as comment_form %}
                {% for field in comment_form %}
                    {{ field|safe }}
                {% endfor %}
                <span id="comment_error"></span>
                <br>
                <input type="submit" value="评论" class="btn btn-dark">
            </form>
        {% else %}
            <span>您尚未登录，登录后方可评论</span>
            <a href="{% url 'login' %}">登录</a>或者
            <a href="{% url 'register' %}">注册</a>
        {% endif %}
    </div>
    </section>
    <section>
        <div class="container w-50">
            <h3>评论列表</h3>
            <div id="comment_list">
            {% get_comment_list topic as comments %}
                {% for comment in comments %}
                    <div class="container w-auto border border-1 py-3">
                        <span class="h3">{{ comment.comment_user.username }}</span>
                        <span class="small">发布于{{ comment.comment_time.date}}:</span>
                        <div id="comment_{{ comment.pk }}" class="p-2">
                        <span>{{ comment.text|safe }}</span>
                        </div>
                        <a href="javascript:reply({{ comment.pk }});">回复</a>
                        {% for reply in comment.root_comment.all %}
                            <div class="reply" >
                                <span class="text-secondary">{{ reply.comment_user.username }}</span>
                                <span>于{{ reply.comment_time.date }}</span>
                                <span>回复</span>
                                <span>{{ reply.reply_to.username }}:</span>
                                <div id="comment_{{ reply.pk }}">
                                    {{ reply.text|safe }}
                                </div>
                                <a href="javascript:reply({{ comment.pk }});">回复</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script rel="script">
        function likeChange(obj, content_type, object_id) {
            var is_like = obj.getElementsByClassName('active').length==0;
            $.ajax({
                url: '{% url "like_change" %}',
                type: 'GET',
                data:{
                    content_type : content_type,
                    object_id : object_id,
                    is_like: is_like,
                },
                cache: false,
                success: function (data) {
                    if(data['status']=='SUCCESS'){
                        // {#更新点赞状态#}
                        var element = $(obj.getElementsByName("thumbs-up-outline"));
                        if(is_like){
                            element.addClass('active');
                        }else {
                            element.removeClass('active');
                        }
                        // {#更新点赞数量#}
                        var liked_num = $(obj.getElementsByClassName('liked-num'));
                        alert(liked_num);
                        liked_num.text(data['liked_num']);
                    }else {
                        alert(data[messsge]);
                    }
                },
                error:function (xhr) {
                    alert("hello");
                }
            });
            location.reload();
        }
        function reply(reply_comment_id){

            $('#reply_comment_id').val(reply_comment_id);
            var html = $('#comment_'+reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
            $('html').animate({scrollTop:$('#comment_form').offset().top-60},300, function () {
                CKEDITOR.instances['id_text'].focus();
            })
        }
        $("#comment_form").submit(function(){
            // 判断是否为空
            $("#comment_error").text('');
            if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }

            // 更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url 'comment:submit_comment' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    if(data['status']=="SUCCESS"){
                        // 插入数据
                        // {#判断是一级评论还是回复#}
                        {#if($('#reply_comment_id').val()==0){#}
                        {#    //插入评论#}
                        {#    var comment_html = '<div id="root_' + data['pk'] + '" class="comment"><span>' + data['username'] + '</span><span> (' + data['comment_time'] + ')：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';#}
                        {##}
                        {#    $("#comment_list").prepend(comment_html);#}
                       // }else {
                        {#    // {#插入回复#}
                        {#     var reply_html ='<div class="reply"><span>' + data['username'] + '</span><span> (' + data['comment_time'] + ')</span><span> 回复 </span><span>' + data['reply_to'] + '：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';#}
                        {#    $("#root_" + data['root_pk']).append(reply_html);#}
                        //{#}#}
                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                    }else{
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
            location.reload();
            return false;
        });

    </script>
{% endblock %}

topic/templates/topic_index.html
{% extends 'base.html' %}
{% load comment_tags %}
{% load crispy_forms_tags %}
{% block title %}
    讨论列表
{% endblock %}
{% block header_extends %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'topic/topic.css' %}">
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock %}
{% block content %}
{#    发起新的讨论#}
    <section>
        <div class="container w-50 py-3">
            {% if user.is_authenticated %}
                <p class="text-center">
                  <button class="btn btn-dark" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                               发起一个新的讨论
                  </button>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                      <div id="add_topic" >
                        <form action="" method="POST" id="topic_form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-8">
                                    {{ topic_form.title|as_crispy_field }}
                                </div>
                                    <div class="col-4">
                                        {{ topic_form.topic_type|as_crispy_field }}
                                    </div>
                                <div class="col-12">
                                    {{ topic_form.content|as_crispy_field }}
                                </div>
                            </div>
                            <span id="topic_error"></span>
                            <input type="submit" value="发起讨论">
                        </form>
                    </div>
                  </div>
                </div>


            {% else %}
                <span>您尚未登录，登录后方可发起讨论哟~</span>
                <a href="{% url 'login' %}" class="btn btn-primary">登录</a>或者
                <a href="{% url 'register' %}" class="btn btn-danger">注册</a>
            {% endif %}
        </div>
    </section>
{#    展示讨论列表#}
    <section>
    <div id="topic_list" class="container w-75">
        <div class="row">
            <div class="col-md-8">
                {% for topic in topics %}
                    <div class="container py-3 border rounded">
                        <h3 ><a class="text-dark" href="{% url 'topic:topic_detail' topic.pk %}">{{ topic.title }}</a></h3>
                        <small>
                            {{ topic.created_time.date }}|&nbsp;
                            分类:
                            <a href="{% url 'topic:topisc_with_type' topic.topic_type.pk %}">
                            <span class="font-weight-normal text-secondary" title="{{ topic.topic_type.type_introduction|safe }}"
                                  data-toggle="tooltip" data-html="true" data-placement="top">{{ topic.topic_type }}</span>
                            </a>
                            <span>评论数：{% get_comment_count topic %}</span>
                        </small>
                        <hr>
                        <small>
                            <p>
                                {{ topic.content|slice:50|safe }}...
                                <a href="{% url 'topic:topic_detail' topic.pk %}" class="text-secondary small">查看更多内容</a>
                            </p>
                        </small>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4 bg-light border rounded">
                <h4 class="text-center py-1">海贼语录</h4>
                <div class="py-2">
                    <p>也许这个世界上并没有偶然，有的只是必然。“缘”不紧不慢的悄然形成，不知所措才是人生！</p>
                    <div class="text-right">
                        <span class="text-right"><em>——雷利</em></span>
                    </div>
                </div>
                <hr>
                <div class="py-2">
                    <p>也许这个世界上并没有偶然，有的只是必然。“缘”不紧不慢的悄然形成，不知所措才是人生！</p>
                    <div class="text-right">
                        <span class="text-right"><em>——雷利</em></span>
                    </div>
                </div>
                <hr>
                <div class="py-2">
                    <p>也许这个世界上并没有偶然，有的只是必然。“缘”不紧不慢的悄然形成，不知所措才是人生！</p>
                    <div class="text-right">
                        <span class="text-right"><em>——雷利</em></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}
{% block script%}
    <script rel="script">
     {#$("#topic_form").submit(function(){#}
     {##}
     {#       // 判断是否为空#}
     {#       $("#topic_error").text('');#}
     {#       // 更新数据到textarea#}
     {#       CKEDITOR.instances['id_text'].updateElement();#}
     {#       // 异步提交#}
            {#$.ajax({#}
            {#    url: "{% url 'topic:add_topic' %}",#}
            {#    type: 'POST',#}
            {#    data: $(this).serialize(),#}
            {#    cache: false,#}
            {#    success: function(data){#}
            {#        alert('aaa');#}
            {#        if(data['status']=="SUCCESS"){#}
            {#            alert('hello');#}
            {#            // 插入数据#}
            {#            var topic_html = "<h3><a > data['title'] </a></h3>"+"<span>评论数：0</span>"#}
            {##}
            {#            $("#topic_list").prepend(topic_html);#}
            {##}
            {#            // 清空编辑框的内容#}
            {#            CKEDITOR.instances['id_text'].setData('');#}
            {#        }else{#}
            {#            alert('world');#}
            {#            // 显示错误信息#}
            {#            $("#comment_error").text(data['message']);#}
            {#        }#}
            {#    },#}
            {#    error: function(xhr){#}
            {#        alert('qq');#}
            {#        console.log(xhr);#}
            {#    }#}
     {#    //   });#}
     {#       location.reload();#}
     {#       return false;#}
     {#   });#}
         $(function () {
        'use strict';
        $('[data-toggle="tooltip"]').tooltip();
    });

    </script>
{% endblock %}

topic/templates/topics_with_type.html
{% extends 'base.html' %}
{% load comment_tags %}
{% block title %}
{% endblock %}
{% block content %}
    <section>
        <div class="container w-50 py-3">
            <div class="card mb-3">
              <img class="card-img-top" src="{{ topic_type.image.url }}" alt="{{ topic_type.type_name }}">
              <div class="card-body">
                <h5 class="card-title">{{ topic_type.type_name }}</h5>
                <p class="card-text">
                    {{ topic_type.type_introduction|safe }}
                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
        </div>
        <div class="container w-50">
            <div>
                <h3 class="text-center">讨论话题</h3>
            </div>
            <div>
                {% for topic in topics %}
                   <div class="container py-3 border rounded">
                        <h3 ><a class="text-dark" href="{% url 'topic:topic_detail' topic.pk %}">{{ topic.title }}</a></h3>
                        <small>
                            {{ topic.created_time.date }}|&nbsp;
                            分类:
                            <a href="{% url 'topic:topisc_with_type' topic.topic_type.pk %}">
                            <span class="font-weight-normal text-secondary" title="{{ topic.topic_type.type_introduction }}" data-toggle="tooltip"
                            data-placement="top">{{ topic.topic_type }}</span>
                            </a>
                            <span>评论数：{% get_comment_count topic %}</span>
                        </small>
                        <hr>
                        <small>
                            <p>
                                {{ topic.content|slice:50|safe }}...
                                <a href="{% url 'topic:topic_detail' topic.pk %}" class="text-secondary small">查看更多内容</a>
                            </p>
                        </small>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}