demo1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import ckeditor_uploader
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('comic/', include('comic.urls')),
    path('', views.home, name='home'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topic/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/24

from django.urls import path, include
from . import views
app_name = 'topic'
urlpatterns = [
    path('', views.topic_index, name='topic_index'),
    path('<int:pk>', views.topic_detail, name='topic_detail'),
    # path('add_topic', views.add_topic, name='add_topic'),
    path('type/<int:type_pk>', views.topics_with_type, name='topisc_with_type'),
]

user/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/5/27


from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('register/', views.register, name='register'),
    path('user_join', views.user_join, name='user_join'),
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block header_extends %}

    {% endblock %}
</head>
<body>
<header>
<div class="navbar-background ">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 ">
          <a class="navbar-brand" href="/">
              海贼王
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">主页 <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'topic:topic_index' %}">讨论</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'comic_index' %}">漫画</a>
                </li>


            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
              <ul class="navbar-nav mr-auto ">
                  {% if not user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
              </li>
                  {% else %}
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'user_info' %}">个人资料</a>
                  <a class="dropdown-item" href="{% url 'user_join' %}">参与的讨论</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}?from={{ request.get_full_path }}">退出登录</a>
                </div>
              </li>
                  {% endif %}
              </ul>
          </div>
    </nav>
</div>
</header>
<main>
    {% block content %}
    {% endblock content %}
</main>
<footer class="text-center text-muted py-4">
    该网站仅供娱乐
</footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% block content %}
    {{ message }}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load comment_tags %}
{% block title %}
    主页
{% endblock %}
{% block header_extends %}
{% endblock %}
{% block content %}
    <section class="py-5">
        <h2 class="text-center">海贼王简介</h2>
        <div class="container w-50">
            <p>拥有财富、名声、权力，这世界上的一切的男人 “海贼王”哥尔·D·罗杰，在被行刑受死之前说了一句话，
                让全世界的人都涌向了大海。“想要我的宝藏吗？如果想要的话，那就到海上去找吧，我全部都放在那里。
                ”，世界开始迎接“大海贼时代”的来临  。</p>
            <p>时值“大海贼时代”，为了寻找传说中海贼王罗杰所留下的大秘宝“ONE PIECE”，无数海贼扬起旗帜，互相争斗。
                有一个梦想成为海贼王的少年叫路飞，他因误食“恶魔果实”而成为了橡皮人，在获得超人能力的同时付出了一辈子无法游泳的代价。
                十年后，路飞为实现与因救他而断臂的香克斯的约定而出海，他在旅途中不断寻找志同道合的伙伴，
                开始了以成为海贼王为目标的冒险旅程   。</p>
        </div>
    </section>
    <section class="py-4 ">
    <div class="container w-75">
        <div class="row">
            <div class="col-md-5 border rounded bg-light float-left">
                <div class="py-2">
                    <a href="{% url 'topic:topic_index' %}">
                    <h3 class="text-center text-muted ">最新讨论话题</h3>
                </a>
                </div>
                <div class="py-2">
                    {% for topic in topics %}
                        <div class="px-3">
                                <a href="{% url 'topic:topic_detail' topic.pk %}">
                                    <h5 class="text-info">{{ topic.title }}</h5>
                                </a>
                             <small>
                                {{ topic.created_time.date }}|&nbsp;
                                关于
                                <a href="{% url 'topic:topisc_with_type' topic.topic_type.pk %}">
                                <span class="font-weight-normal text-secondary" title="{{ topic.topic_type.type_introduction|safe }}"
                                  data-toggle="tooltip" data-html="true" data-placement="top">{{ topic.topic_type }}</span>

                                </a>
                                <span>评论数：{% get_comment_count topic %}</span>
                            </small>
                            <hr>
                        </div>
                    {% endfor%}
                </div>
            </div>
            <div class="col-md-2">

            </div>
            <div class="col-md-5 border rounded bg-light float-right">
                <div class="py-2">
                    <a href="{% url "comic_index" %}">
                        <h3 class="text-muted text-center">最新海贼王漫画</h3>
                    </a>
                </div>
                <div class="py-2">
                    {% for chapter in chapters %}
                        <div class="px-3">
                            <a href="{% url 'chapter_detail' chapter.chapter_number 0 %}">
                                <h5 class="text-info">{{ chapter.chapter_name }}</h5>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}